# Generated by Django 5.0 on 2023-12-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_achievements_user_ahievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ahievements',
            field=models.ManyToManyField(blank=True, null=True, to='authapp.achievements'),
        ),
    ]
