# Generated by Django 5.0 on 2023-12-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_user_ahievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ahievements',
            new_name='achievements',
        ),
    ]
