# Generated by Django 5.0 on 2023-12-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_rename_achievements_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(null=True, to='authapp.achievement'),
        ),
    ]
