# Generated by Django 5.0 on 2023-12-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_user_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(to='authapp.achievement'),
        ),
    ]
