# Generated by Django 5.0 on 2023-12-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_user_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='authapp.achievement'),
        ),
    ]
