# Generated by Django 5.0 on 2023-12-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_student_time_create_student_time_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
