# Generated by Django 5.0 on 2023-12-11 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_user_avatar_alter_user_group_alter_user_role_and_more'),
        ('backend', '0004_remove_student_group_delete_group_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('lesson_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('online', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authapp.group')),
            ],
        ),
    ]
