# Generated by Django 5.0 on 2023-12-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_achievements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievements',
        ),
    ]
