# Generated by Django 4.2.3 on 2023-08-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('tutor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=100)),
                ('group_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('group_id', models.IntegerField(blank=True)),
                ('training_course', models.CharField(blank=True, max_length=100)),
                ('biography', models.CharField(blank=True, max_length=100)),
                ('achievements', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('lecture', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
