# Generated by Django 4.2.3 on 2023-08-04 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_group_lesson_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
